services:
  activemq:
    image: apache/activemq-artemis:latest
    restart: unless-stopped
    env_file:
      - ./deploy/backend.env
    environment:
      ARTEMIS_USER: ${ACTIVEMQ_USER}
      ARTEMIS_PASSWORD: ${ACTIVEMQ_PASSWORD}

  auth-service:
    image: 329350276565.dkr.ecr.ap-southeast-1.amazonaws.com/insureth-auth-service:latest
    restart: unless-stopped
    env_file:
      - ./deploy/backend.env
    depends_on:
      activemq:
        condition: service_started

  insurance-service:
    image: 329350276565.dkr.ecr.ap-southeast-1.amazonaws.com/insureth-insurance-service:latest
    restart: unless-stopped
    env_file:
      - ./deploy/backend.env
    depends_on:
      activemq:
        condition: service_started
      auth-service:
        condition: service_started

  notification-service:
    image: 329350276565.dkr.ecr.ap-southeast-1.amazonaws.com/insureth-notification-service:latest
    restart: unless-stopped
    env_file:
      - ./deploy/backend.env
    depends_on:
      activemq:
        condition: service_started

  gateway-service:
    image: 329350276565.dkr.ecr.ap-southeast-1.amazonaws.com/insureth-gateway-service:latest
    restart: unless-stopped
    env_file:
      - ./deploy/backend.env
    depends_on:
      auth-service:
        condition: service_started
      insurance-service:
        condition: service_started
    ports:
      - "8080:8080"
